apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      serviceAccountName: leader-election-sa
      containers:
        - name: leader-election
          image: leader-election:latest
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          emptyDir: {}
