apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-deployment
  labels:
    app: leader-election
spec:
  replicas: 5 # Set the number of replicas to 5
  selector:
    matchLabels:
      app: leader-election
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      containers:
        - name: leader-election
          image: leader-election:latest # Use the local image built
          ports:
            - containerPort: 8080
          imagePullPolicy: Never # Since we're using a locally built image
